version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-foods-postgres
    environment:
      POSTGRES_DB: fsw-foods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
